### ISSUE TITLE
ubuntu18.0 上使用老报错

### ISSUE THREAD

**Issue by dsasdfsdff12312312** [Awrrays/Shipwreck#2]
decodeAndRun.cpp:13:16: error: ‘VirtualAllocExNuma’ was not declared in this scope; did you mean ‘VirtualAllocEx’?
   13 |  LPVOID addr = VirtualAllocExNuma(GetCurrentProcess(), NULL, sizeof(Ciphertext), MEM_COMMIT, PAGE_READWRITE, 0);
      |                ^~~~~~~~~~~~~~~~~~
      |                VirtualAllocEx
/Shipwreck/Output# x86_64-w64-mingw32-gcc -m64 -s -w -o temp.exe decodeAndRun.cpp
x86_64-w64-mingw32-gcc: fatal error: cannot execute ‘cc1plus’: execvp: No such file or directory

**Comment by Awrrays** [comment]
具体截图发一下

**Comment by dsasdfsdff12312312** [comment]
![image](https://user-images.githubusercontent.com/121791712/212798573-91d1a5c4-ecfd-4661-856d-2a5fd2fb392c.png)
![image](https://user-images.githubusercontent.com/121791712/212799185-f9ea5744-f9f4-442d-8cec-328cda75bdcd.png)
![image](https://user-images.githubusercontent.com/121791712/212799469-bd3d6da7-361a-4bf3-9396-b39b2af95fa6.png)

这是我遇到的集中情况

**Comment by Awrrays** [comment]
两种方案
1、在Ubuntu使用， 在decodeAndRun.cpp中引入#include <winbase.h>，该头文件包含VirtualAllocExNuma函数
2、在Windows使用，在https://github.com/Awrrays/Shipwreck/releases/download/1.0/x86_64-12.2.0-release-win32-seh-rt_v10-rev1.7z下载mingw for windows
推荐第二种，因为我只在windows和mac上测试过，ubuntu上可能会有其他的问题
